package no.ntnu.oskarlothe.model;

import java.time.LocalDate;

/**
 * A class representing a schedule in the application.
 * A schedule consists of a list of days, as well as a list of repeating tasks.
 * <br/>
 * <br/>
 * The dayList field only contains days that holds data manipulated by the user.
 * All other "dead" days will be generated by the dayGenerator object.
 * 
 * @author Oskar Lothe
 * @version 1.0-SNAPSHOT
 */
public class Schedule {
    private DayList days;

    private TaskList repeatingTasks;

    /**
     * Default constructor for the Schedule class.
     */
    public Schedule() {
        this.days = new DayList();
        this.repeatingTasks = new TaskList();
    }

    /**
     * Returns the day for a spesific date.
     * 
     * @param date date of the day
     * @return day object matching the given date
     */
    public Day getDay(LocalDate date) {
        return DayGenerator.generate(date, this.days, this.repeatingTasks);
    }

    /**
     * Returns the list of days.
     * 
     * @return DayList object
     */
    public DayList getDayList() {
        return this.days;
    }

    /**
     * Returns the list of repeating tasks.
     * 
     * @return TaskList containing repeating task objects
     */
    public TaskList getRepeatingTasks() {
        return this.repeatingTasks;
    }

    /**
     * Returns all tasks from the list of days.
     * 
     * @return all tasks from the individual days
     */
    public TaskList getAllDayTasks() {
        TaskList result = new TaskList();

        this.days.forEach(
            (day) -> {
                day.forEach(
                    (task) -> {
                        result.add(task);
                    }
                );
            }
        );

        return result;
    }

    /**
     * Returns a list of all the tasks in the schedule; both tasks from the days and
     * the repeating tasks.
     * 
     * @return TaskList object containing all tasks
     */
    public TaskList getAllTasks() {
        TaskList result = this.getAllDayTasks().clone();

        result.addAll(this.repeatingTasks);

        return result;
    }
}
